### Matching Registrants between 2 years of data -- This is a prototype!

In [1]:
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 30, 2018

This is my python version of the guest record matching project.

The application will match the guests record in different years and show versions.

@author: Grejell
"""
import numpy as np
import pandas as pd
import os

Set the directory

In [2]:
os.chdir('C:/Users/Grejell/AnacondaProjects/IDMatchingProject/')

Load the 2 data sets to match

In [3]:
yearOneData = pd.read_csv("./dta/yearOne.csv", engine='python')
yearTwoData = pd.read_csv("./dta/yearTwo.csv", engine='python')

Retain the columns to be used for matching

In [4]:
yearOneData = yearOneData[["10DigitCardNumber", "FirstName", "Surname", "Position", "Email", "CompanyName"]]
yearTwoData = yearTwoData[["10DigitCardNumber", "FirstName", "Surname", "Position", "Email", "CompanyName"]]

This function removes non alpha numeric characters and set all the strings to lower case

In [5]:
def function_1(df):
    columns = ["FirstName", "Surname", "Position", "Email", "CompanyName"]
    for column in columns:
        df[column] = df[column].str.replace(r'[^A-z0-9]', '').str.lower()
    return df

yearOneData = function_1(yearOneData)
yearTwoData = function_1(yearTwoData)

This function replaces blank cells to Nan and create a column that counts the number of Nan from First Name to Company Name

In [6]:
def function_2(df):
    df.replace(r'^\s*$', np.nan, regex=True, inplace = True)
    df['countNan'] = df.loc[:,'FirstName':'CompanyName'].count(axis=1)
    return df

yearOneData = function_2(yearOneData)
yearTwoData = function_2(yearTwoData)

This function concatenates the columns for the reference of matching between the data frames

In [7]:
def function_3(df):
    newCols = ['combo1', 'combo2', 'combo3', 'combo4', 'combo5', 'combo6', 'combo7', 'combo8', 'combo9', 'combo10', 'combo11']
    for cols in newCols:
        df.cols = pd.Series()
    df['Email'] = df['Email'].str.replace(r'_', '')
    df.loc[df.countNan > 2,'combo1' ] = df.FirstName+df.Surname+df.Position+df.Email+df.CompanyName
    df.loc[pd.notnull(df.FirstName) & pd.notnull(df.Surname) & pd.notnull(df.Position) & pd.notnull(df.CompanyName), 'combo2' ] = df.FirstName+df.Surname+df.Position+df.CompanyName
    df.loc[pd.notnull(df.FirstName) & pd.notnull(df.Surname) & pd.notnull(df.Email) & pd.notnull(df.CompanyName),'combo3' ] = df.FirstName+df.Surname+df.Email+df.CompanyName
    df.loc[pd.notnull(df.FirstName) & pd.notnull(df.Surname) & pd.notnull(df.CompanyName), 'combo4' ] = df.FirstName+df.Surname+df.CompanyName
    df.loc[pd.notnull(df.FirstName) & pd.notnull(df.Surname) & pd.notnull(df.Position), 'combo5' ] = df.FirstName+df.Surname+df.Position
    df.loc[pd.notnull(df.Position) & pd.notnull(df.Email) & pd.notnull(df.CompanyName), 'combo6' ] = df.Position+df.Email+df.CompanyName
    df.loc[pd.notnull(df.FirstName) & pd.notnull(df.Surname) & pd.notnull(df.Email), 'combo7' ] = df.FirstName+df.Surname+df.Email
    df['combo8'] = df.Email
    df.loc[pd.notnull(df.Position) & pd.notnull(df.Email), 'combo9' ] = df.Position+df.Email
    df.loc[pd.notnull(df.FirstName) & pd.notnull(df.Surname), 'combo10'] = df.FirstName+df.Surname
    df.loc[pd.notnull(df.Position) & pd.notnull(df.CompanyName), 'combo11'] = df.Position+df.CompanyName
    return df

yearOneData = function_3(yearOneData)
yearTwoData = function_3(yearTwoData)

This is a function that merges/matches data1 to data2 using the concatenation combos

In [41]:
def function_4(df1, df2):
    data = df2[['10DigitCardNumber', 'FirstName', 'Surname', 'Position', 'Email', 'CompanyName']]    
    combos = ['combo1', 'combo2', 'combo3', 'combo4', 'combo5', 'combo6', 'combo7', 'combo8', 'combo9', 'combo10', 'combo11']
    for combo in combos:
        mergeData = pd.merge(df2[['10DigitCardNumber', combo]], df1.loc[pd.notnull(df1[combo]),['10DigitCardNumber', combo]], how = 'left', on = combo)
        mergeData = mergeData[mergeData['10DigitCardNumber_y'].notnull()]
        #mergeData = mergeData.drop([combo], axis = 1)
        mergeData = mergeData.rename(columns = {'10DigitCardNumber_x': '10DigitCardNumber', '10DigitCardNumber_y': combo+'10DigitCardNumber'})
        data = pd.merge(data, mergeData, how = 'left', on = '10DigitCardNumber').drop_duplicates()
    return data

data = function_4(yearOneData, yearTwoData)

In [42]:
data.head()

,10DigitCardNumber,FirstName,Surname,Position,Email,CompanyName,combo110DigitCardNumber,combo210DigitCardNumber,combo310DigitCardNumber,combo410DigitCardNumber,combo510DigitCardNumber,combo610DigitCardNumber,combo710DigitCardNumber,combo810DigitCardNumber,combo910DigitCardNumber,combo1010DigitCardNumber,combo1110DigitCardNumber
0,3797000215,caio,gaetan,tradeoperation,caiogaetanalghuraircom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3797000964,syeda,khan,freelanceadminexecutive,syedakhan1yahoocom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.997004e+09,7.997004e+09,NaN,7.997004e+09,NaN
2,3797001570,basheer,qafisheh,generalmanager,blueskycom1111gmailcom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.197007e+09,7.197007e+09,NaN,7.197007e+09,NaN
3,3797001588,hamzah,alhamzah,chief,gooldangalhotmailcom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3797003188,larisa,dsouza,student,larisadsouzaoutlookcom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
data['match'] = pd.Series()
data.loc[pd.notnull(data.combo1), 'match'] = data['combo110DigitCardNumber']
data.loc[pd.isnull(data.combo1) & pd.notnull(data.combo2), 'match'] = data['combo210DigitCardNumber']
data.loc[pd.isnull(data.combo1) & pd.isnull(data.combo2) & pd.notnull(data.combo3), 'match'] = data['combo310DigitCardNumber']
data.loc[pd.isnull(data.combo1) & pd.isnull(data.combo2) & pd.isnull(data.combo3) & pd.notnull(data.combo4), 'match'] = data['combo410DigitCardNumber']
data.loc[pd.isnull(data.combo1) & pd.isnull(data.combo2) & pd.isnull(data.combo3) & pd.isnull(data.combo4) & pd.notnull(data.combo5), 'match'] = data['combo510DigitCardNumber']
data.loc[pd.isnull(data.combo1) & pd.isnull(data.combo2) & pd.isnull(data.combo3) & pd.isnull(data.combo4) & pd.isnull(data.combo5) & pd.notnull(data.combo6), 'match'] = data['combo610DigitCardNumber']
data.loc[pd.isnull(data.combo1) & pd.isnull(data.combo2) & pd.isnull(data.combo3) & pd.isnull(data.combo4) & pd.isnull(data.combo5) & pd.isnull(data.combo6) & pd.notnull(data.combo7), 'match'] = data['combo710DigitCardNumber']
data.loc[pd.isnull(data.combo1) & pd.isnull(data.combo2) & pd.isnull(data.combo3) & pd.isnull(data.combo4) & pd.isnull(data.combo5) & pd.isnull(data.combo6) & pd.isnull(data.combo7) & pd.notnull(data.combo8), 'match'] = data['combo810DigitCardNumber']
data.loc[pd.isnull(data.combo1) & pd.isnull(data.combo2) & pd.isnull(data.combo3) & pd.isnull(data.combo4) & pd.isnull(data.combo5) & pd.isnull(data.combo6) & pd.isnull(data.combo7) & pd.isnull(data.combo8) & pd.notnull(data.combo9), 'match'] = data['combo910DigitCardNumber']
data.loc[pd.isnull(data.combo1) & pd.isnull(data.combo2) & pd.isnull(data.combo3) & pd.isnull(data.combo4) & pd.isnull(data.combo5) & pd.isnull(data.combo6) & pd.isnull(data.combo7) & pd.isnull(data.combo8) & pd.isnull(data.combo9) & pd.notnull(data.combo10), 'match'] = data['combo1010DigitCardNumber']
data.loc[pd.isnull(data.combo1) & pd.isnull(data.combo2) & pd.isnull(data.combo3) & pd.isnull(data.combo4) & pd.isnull(data.combo5) & pd.isnull(data.combo6) & pd.isnull(data.combo7) & pd.isnull(data.combo8) & pd.isnull(data.combo9) & pd.isnull(data.combo10) & pd.notnull(data.combo11), 'match'] = data['combo1110DigitCardNumber']

AttributeError: 'DataFrame' object has no attribute 'combo1'

In [40]:
data

,10DigitCardNumber,FirstName,Surname,Position,Email,CompanyName,combo1,combo110DigitCardNumber,combo2,combo210DigitCardNumber,...,combo710DigitCardNumber,combo8,combo810DigitCardNumber,combo9,combo910DigitCardNumber,combo10,combo1010DigitCardNumber,combo11,combo1110DigitCardNumber,match
0,3797000215,caio,gaetan,tradeoperation,caiogaetanalghuraircom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3797000964,syeda,khan,freelanceadminexecutive,syedakhan1yahoocom,NaN,NaN,NaN,NaN,NaN,...,7.997004e+09,syedakhan1yahoocom,7.997004e+09,NaN,NaN,syedakhan,7.997004e+09,NaN,NaN,NaN
2,3797001570,basheer,qafisheh,generalmanager,blueskycom1111gmailcom,NaN,NaN,NaN,NaN,NaN,...,7.197007e+09,blueskycom1111gmailcom,7.197007e+09,NaN,NaN,basheerqafisheh,7.197007e+09,NaN,NaN,NaN
3,3797001588,hamzah,alhamzah,chief,gooldangalhotmailcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3797003188,larisa,dsouza,student,larisadsouzaoutlookcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,3797003347,sneha,sharma,manager,shivangimathur30gmailcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3797003355,ronak,gera,generalmanager,geraronak9yahoocom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,3797003484,sathar,zedie,instructor,amforzedhotmailcom,NaN,NaN,NaN,NaN,NaN,...,7.197001e+09,amforzedhotmailcom,7.197001e+09,instructoramforzedhotmailcom,7.197001e+09,satharzedie,7.197001e+09,NaN,NaN,NaN
8,3797003673,shakir,mohammad,salesrepresentative,rajujhansihotmailcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3797004285,sd,kiran,NaN,gurukirankiranhotmailcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,3797004328,evana,a,generalmanager,podravkapodravkaae,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,3797004436,muhammed,ali,exportmanager,hamitcilcilsancikolatacom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,muhammedali,7.197006e+09,NaN,NaN,NaN
12,3797004524,rashi,kothari,freelanceconsultant,rashikotharihotmailcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,3797004816,samir,bedi,managingdirector,samirbrandskonnectcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,3797006163,abbas,lalljee,managingpartner,alalljeeseiseigourmentcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,abbaslalljee,7.897002e+09,NaN,NaN,NaN
15,3797006165,abdullah,mujadidy,managingdirector,mujadidymujezatcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,3797006967,julia,rex,student,juliarexgmailcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,3797006982,ibrahim,awadh,ceo,im8411gmailcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,3797007011,sara,raziq,chefinpastry,chefsarafazal22yahoocom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,3797007264,fakhar,yousaf,owner,dot2printyahoocom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,3797007286,simin,kodakadan,operationsmanager,siminvkgmailcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,3797007299,raheel,tahir,owner,raheeltahirgmailcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,3797007313,elisabeta,gorgovan,assistanthotelmanager,elisadumitruyahoocom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,3797007697,frederique,simon,pastrybakerycategorymanager,frederiquechefmiddleeastcom,NaN,NaN,NaN,NaN,NaN,...,7.197001e+09,frederiquechefmiddleeastcom,7.197001e+09,NaN,NaN,frederiquesimon,7.197001e+09,NaN,NaN,NaN
24,3797008099,farheen,panja,NaN,rizuuanpanjahotmailcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,3797008467,joan,bakerly,student,joanbakerlyhotmailcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,3797008525,afroze,anisnawaz,seniormarketingexecutive,afrozeanisnawazgmailcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,3797008668,deepa,jaisingh,bloggerandwriter,deepa2984gmailcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,3797008818,mashaelmustafa,faqihi,freelanceinteriordesigner,mashaelfgmailcom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,3797008825,zoopeer,ershadpoor,projectmanager,zooperyahoocom,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41265,3797013544,mehdi,mrpangtanamiri,manager,infozubinteacom,zubintea,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41266,3797007256,christoph,kind,managingdirector,gbraunzhugermanycom,zuckerhandelsuniongmbhcokg,NaN,NaN,christophkindmanagingdirectorzuckerhandelsunio...,7.997003e+09,...,NaN,NaN,NaN,NaN,NaN,christophkind,7.997003e+09,managingdirectorzuckerhandelsuniongmbhcokg,7.997003e+09,NaN
41267,3797021341,mohammed,alsaeh,businessman,mohds1434gmailcom,zuhorelmuhammadia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41268,3797017529,saad,said,manager,saadorghotmailcom,zuhouralsahara,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41269,3797005914,nanni,espiritu,assistant,pazuhourgroupcom,zuhourgroup,NaN,NaN,NaN,NaN,...,NaN,pazuhourgroupcom,7.897000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41270,3797020520,elie,badawi,generalmanager,ebadawizuhourgroupae,zuhourgroup,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41271,3709037540,osama,ghosen,purchasingmanager,oghosenzuhourgroupcom,zuhourgroup,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41272,3797028346,rajish,kumar,purchasingmanager,rkumarzuhourgroupcom,zuhourgroup,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41273,3798001678,ghenwa,tarabay,marketingmanager,gtarabayzuhourgroupcom,zuhourgroup,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41274,3797025774,paulineanne,espiritu,personalassistanttothechairman,ggorospezuhourgroupcom,zuhourgroupofrestaurants,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41275,3797026166,suresh,kumar,cateringmanager,skumarzulekhahospitalscom,zulekhahospital,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,sureshkumar,7.197001e+09,NaN,NaN,NaN
41276,3797026166,suresh,kumar,cateringmanager,skumarzulekhahospitalscom,zulekhahospital,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,sureshkumar,7.197009e+09,NaN,NaN,NaN
41277,3797022872,mukesh,chhabria,ceo,mukeshzulkomdubaicom,zulkomtradingfze,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41278,3797030346,claudie,chatelard,globalprojectmanager,claudiezumarestaurantae,zuma,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41279,3797003655,florencia,beschtedt,gmzumadubai,florenciazumarestaurantae,zuma,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41280,3797012263,carlos,delosmozos,executivechef,carloszumarestaurantae,zumarestaurant,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41281,3797025554,veronica,frances,exhibitionsmanager,veronicafranceszumexcom,zumex,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41282,3797020492,ninad,save,marketinghead,ninadzummoin,zummoindia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41283,3797020484,arpit,patwa,financehead,arpitzummoin,zummoindia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41284,3797020476,rahul,popat,saleshead,rahulzummoin,zummoindia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41285,3797020465,dhaval,panchal,technicalhead,dhavalfrootlein,zummoindia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41286,3797001714,okyar,gokpinar,generalmanager,okyargokpinarzumotjo,zumotgroup,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41287,3797003068,hannah,joao,regionalmarketingmanager,hannahjoaogmailcom,zumtobelgroup,NaN,NaN,NaN,NaN,...,7.197003e+09,hannahjoaogmailcom,7.197003e+09,NaN,NaN,hannahjoao,7.197003e+09,NaN,NaN,NaN
41288,3797005869,thomas,easo,salesmanager,thomaseasozurichfooddubaicom,zurichfoods,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41289,3797003899,jino,anirudhan,salescoordinator,mikhilzurichfooddubaicom,zurichfoodstufftradingllc,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41290,3797021306,moahmmad,rafiael,ceo,mohammadrafiaee20gmailcom,zuse,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41291,3797028817,jove,sucgang,operationsmanager,jovezushisharjahgmailcom,zushi,NaN,NaN,NaN,NaN,...,7.197004e+09,jovezushisharjahgmailcom,7.197004e+09,NaN,NaN,jovesucgang,7.197004e+09,NaN,NaN,NaN
41292,3797003910,michelle,san,manager,mitchzushigmailcom,zushi,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41293,3797012625,muhammed,aslam,marketingmanager,mpmaslamgmailcom,zytoongeneraltradingllc,muhammedaslammarketingmanagermpmaslamgmailcomz...,7.997002e+09,muhammedaslammarketingmanagerzytoongeneraltrad...,7.997002e+09,...,7.997002e+09,mpmaslamgmailcom,7.997002e+09,marketingmanagermpmaslamgmailcom,7.997002e+09,muhammedaslam,7.997002e+09,marketingmanagerzytoongeneraltradingllc,7.997002e+09,7.997002e+09
41294,3797005149,zeeshanabdul,hafeez,ceo,zzengroupoutlookcom,zzengroup,zeeshanabdulhafeezceozzengroupoutlookcomzzengroup,7.197006e+09,zeeshanabdulhafeezceozzengroup,7.197006e+09,...,7.197006e+09,zzengroupoutlookcom,7.197006e+09,ceozzengroupoutlookcom,7.197006e+09,zeeshanabdulhafeez,7.197006e+09,ceozzengroup,7.197006e+09,7.197006e+09

Save data as matchedFile.csv

In [ ]:
data = data[['10DigitCardNumber', "FirstName", "Surname", "Position", "Email", "CompanyName", 'match']]
#data = pd.merge(yearTwoData, data, how = 'left', on = '10DigitCardNumber').drop_duplicates()

In [ ]:
#dataFinal = data[['10 Digit Card Number', 'match']]
data.to_csv(r'./dta/matchedFile.csv', index = False)